const VIEWDATA = "VIEWDATA"
const COUNT_COUNTRY_DATA_FETCH = 'COUNT_COUNTRY_DATA_FETCH'
const ALL_DATA_FETCH_BY_DATE = 'ALL_DATA_FETCH_BY_DATE'
export {VIEWDATA,COUNT_COUNTRY_DATA_FETCH,ALL_DATA_FETCH_BY_DATE}

