const VIEWDATA = "VIEWDATA"
const COUNT_COUNTRY_DATA_FETCH = 'COUNT_COUNTRY_DATA_FETCH'
const ALL_DATA_FETCH_BY_DATE = 'ALL_DATA_FETCH_BY_DATE'
const DELETE_MAX_ENTRY= 'DELETE_MAX_ENTRY'
const GETDATA_DATEANDCOUNTRYMATCHING='GETDATA_DATEANDCOUNTRYMATCHING'
export {VIEWDATA,COUNT_COUNTRY_DATA_FETCH,ALL_DATA_FETCH_BY_DATE,DELETE_MAX_ENTRY,GETDATA_DATEANDCOUNTRYMATCHING}

